### ISSUE TITLE
Minor documentation mistype

### ISSUE THREAD

**Issue by NanDotWang** [JohnSundell/Flow#2]
Hi, 

Thanks for open sourcing great works :)  

Just found a minor documentation mistype, maybe you can fix it in your future commits : 
![image](https://cloud.githubusercontent.com/assets/1992765/19235687/7cceb7ce-8ef3-11e6-9adf-5ceac6400979.png)

" either asynchronous or asynchronous" -> " either synchronous or asynchronous"

Cheers, 
Nan

**Comment by JohnSundell** [comment]
Ah, thanks @benxavior! Will fix it :)
